module.exports = [
  '1_Introduction-1_DeclarativeRendering-1',
  '1_Introduction-1_DeclarativeRendering-2',
  '1_Introduction-2_Conditionals&Loops-1',
  '1_Introduction-2_Conditionals&Loops-2',
  '1_Introduction-3_HandlingUserInput-1',
  '1_Introduction-3_HandlingUserInput-2',
  '1_Introduction-4_ComposingWithComponents-1',
  '2_TheVueInstance-1_Data&Methods-1',
  '2_TheVueInstance-2_InstanceLifecycleHooks-1',
  '3_TemplateSyntax-1_Interpolations-1',
  '3_TemplateSyntax-2_Directives-1',
  '3_TemplateSyntax-3_Shorthands-1',
  'index',
];